name: Deploy to Preprod
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'contracts/**'
      - 'preprod-deployment/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Copy Contract
        run: |
          cp contracts/gatecheck.compact preprod-deployment/contracts/src/bboard.compact

      - name: Compile Contract
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/midnightntwrk/compact/releases/latest/download/compact-installer.sh | sh
          export PATH="$HOME/.local/bin:$PATH"
          compact update
          cd preprod-deployment/contracts
          compact compile src/bboard.compact ./src/managed/bboard
          
          # Patch the generated JS files to bypass the version mismatch check!
          sed -i 's/0.19.0/0.16.0/g' src/managed/bboard/contract/*
        
      - name: Install dependencies
        run: |
          cd preprod-deployment
          npm install
          npm install --no-save tsx
          
      - name: Build Contract Bindings
        run: |
          cd preprod-deployment/contracts
          npm run build
          
      - name: Deploy Contract
        run: |
          cd preprod-deployment/cli
          npx tsx src/launcher/deploy-gatecheck.ts
        env:
          WALLET_SEED: ${{ secrets.WALLET_SEED }}
